In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns = ["cgpa","profile_score" , "lpa"])

In [3]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):
        parameters["W" +str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters["b"+ str(l)] = np.zeros((layer_dims[l],1))

    return parameters

In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
def linear_forward(A_prev , W,b):
    z = np.dot(W.T ,A_prev)+b
    return z

# forward propgation

In [7]:
def L_layer_forward(X,parameters):
    A=X
    L=len(parameters)//2 #numbers of layers in neural network

    for l in range(1 , L+1):
        A_prev = A
        W1 = parameters["W"+str(l)]
        b1 = parameters["b" +str(l)]
        print("A"+str(l-1)+":" ,A_prev)
        print("W" + str(l) +":", W1)
        print("b"+str(l)+":",b1)
        print("--"*20)

        A= linear_forward(A_prev , W1,b1)
        print("A"+str(l)+":" , A)
        print("**"*20)

    return A,A_prev

In [8]:
X= df[["cgpa","profile_score"]].values[0].reshape(2,1) # shape (no of features , no of training example)
y = df[["lpa"]].values[0][0]
parameters = initialize_parameters([2,2,1])

In [9]:
y_hat , A1 =L_layer_forward(X,parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************

In [10]:
y_hat = y_hat[0][0]
y_hat

0.32000000000000006

In [11]:
def update_parameters(parameters , y, y_hat , A1 , X):
    parameters['W2'][0][0] =parameters['W2'][0][0] + (.001*2*(y-y_hat)*A1[0][0])
    parameters['W2'][1][0] =parameters['W2'][1][0] + (.001*2*(y-y_hat)*A1[1][0])
    parameters['b2'][0][0] =parameters['W2'][1][0] + (.001*2*(y-y_hat))
    
    parameters['W1'][0][0] =parameters['W1'][0][0] + (.001*2*(y-y_hat)*parameters["W2"][0][0]*X[0][0])
    parameters['W1'][0][1] =parameters['W1'][0][1] + (.001*2*(y-y_hat)*parameters["W2"][0][0]*X[1][0])
    parameters['b1'][0][0] =parameters['b1'][0][0] + (.001*2*(y-y_hat)*parameters["W2"][0][0])
    
    parameters['W1'][1][0] =parameters['W1'][1][0] + (.001*2*(y-y_hat)*parameters["W2"][1][0]*X[0][0])
    parameters['W1'][1][1] =parameters['W1'][1][1] + (.001*2*(y-y_hat)*parameters["W2"][1][0]*X[1][0])
    parameters['b1'][1][0] =parameters['b1'][1][0] + (.001*2*(y-y_hat)*parameters["W2"][1][0])

In [12]:
update_parameters(parameters , y,y_hat,A1,X)

In [13]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [14]:
epochs = 100
parameters = initialize_parameters([2,2,1])
for i in range(epochs):
    
    loss = []
    
    for j in range(df.shape[0]):
        x = df[["cgpa" , "profile_score"]].values[j].reshape(2,1)
        y = df[["lpa"]].values[j][0]

# parameter initialixzation

        y_hat , A1 = L_layer_forward(x , parameters)
        y_hat = y_hat[0][0]
        update_parameters(parameters,y,y_hat,A1,x)

        loss.append((y-y_hat)**2)
    print('epoch -',i+1 ,"loss" , np.array(loss).mean())

parameters

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************
A0: [[7]
 [9]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.111776]
 [0.111776]]
b2: [[0.119136]]
----------------------------------------
A2: [[0.50054357]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1: [[0.0019667]
 [0.0019667]]
----------------------------------------
A1: [[1.83539945]
 [1.87200826]]
****************************************
A1: [[1.83539945]
 [1.87200826]]
W2: [[0.12712927]
 [0.12712927]]
b2: [[0.13612818]]
----------------------------------------
A2: [[0.6074482]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1: [[0.00355129]
 [0.00355555]]
----------------------------------------
A1: [[2.11350869]
 [2.26036654]]
****************************************
A1: [[2.11350869]
 [2.26036654]]
W2: [[0.14692424]
 [0.14731907]]
b2: [[0.15810417]]
----------------------------------------
A2: [[0.80162493]]
****************************************
epoch - 1 loss 25.321744156025517
A0: [[8]
 [8]]
W1: [[0.13482804 0.15847776]
 [0.1349909  0.15884991]]
b1: [[0.00569748]
 [0.0057292 ]]
----------------------------------------
A1: [[2.16424899]
 [2.54435052]]
****************************************
A1: [[2.16424899]
 [2.54435052]]
W2: [[0.17312488]
 [0.17534027]]
b2: [[0.18773702]]
----------------------------------------
A2: [[1.00854947]]
****************************************
A0: [[7]
 [9]]
W1: [[0.1437341  0.16738383]
 [0.14411185 0.16797086]]
b1: [[0.00681073]
 [0.00686932]]
----------------------------------------
A1: [[2.30995614]
 [2.69029382]]
****************************************
A1: [[2.30995614]
 [2.69029382]]
W2: [[0.18607337]
 [0.19056287]]
b2: [[0.19654577]]
----------------------------------------
A2: [[1.13903718]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.15475619 0.18155508]
 [0.15553536 0.18265822]]
b1: [[0.00838532]
 [0.00850125]]
----------------------------------------
A1: [[2.49227603]
 [2.92441391]]
****************************************
A1: [[2.49227603]
 [2.92441391]]
W2: [[0.20391068]
 [0.21133712]]
b2: [[0.21905904]]
----------------------------------------
A2: [[1.34529793]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.16744187 0.20269788]
 [0.16886056 0.20486689]]
b1: [[0.0104996 ]
 [0.01072211]]
----------------------------------------
A1: [[2.87403566]
 [3.48261418]]
****************************************
A1: [[2.87403566]
 [3.48261418]]
W2: [[0.22711228]
 [0.23856167]]
b2: [[0.24787107]]
----------------------------------------
A2: [[1.73141811]]
****************************************
epoch - 2 loss 18.320004165722047
A0: [[8]
 [8]]
W1: [[0.18100301 0.23524462]
 [0.18336278 0.23967222]]
b1: [[0.01321183]
 [0.01362256]]
----------------------------------------
A1: [[2.92813816]
 [3.8129573 ]]
****************************************
A1: [[2.92813816]
 [3.8129573 ]]
W2: [[0.25739647]
 [0.27525854]]
b2: [[0.28579571]]
----------------------------------------
A2: [[2.08903719]]
****************************************
A0: [[7]
 [9]]
W1: [[0.18921518 0.24345679]
 [0.1922245  0.24853394]]
b1: [[0.01423835]
 [0.01473027]]
----------------------------------------
A1: [[3.06876509]
 [3.95573325]]
****************************************
A1: [[3.06876509]
 [3.95573325]]
W2: [[0.26858759]
 [0.28983138]]
b2: [[0.29365331]]
----------------------------------------
A2: [[2.26438116]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.20014476 0.25750911]
 [0.20415354 0.26387128]]
b1: [[0.01579972]
 [0.01643442]]
----------------------------------------
A1: [[3.25820367]
 [4.20020184]]
****************************************
A1: [[3.25820367]
 [4.20020184]]
W2: [[0.28537753]
 [0.31147414]]
b2: [[0.31694538]]
----------------------------------------
A2: [[2.55501776]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.21287024 0.27871824]
 [0.21822616 0.28732564]]
b1: [[0.01792063]
 [0.01877986]]
----------------------------------------
A1: [[3.7009857 ]
 [4.86027872]]
****************************************
A1: [[3.7009857 ]
 [4.86027872]]
W2: [[0.30782644]
 [0.34041338]]
b2: [[0.34730334]]
----------------------------------------
A2: [[3.14106851]]
****************************************
epoch - 3 loss 9.473661050729625
A0: [[8]
 [8]]
W1: [[0.22585131 0.3098728 ]
 [0.23281    0.32232686]]
b1: [[0.02051684]
 [0.02169662]]
----------------------------------------
A1: [[3.68980727]
 [5.07929387]]
****************************************
A1: [[3.68980727]
 [5.07929387]]
W2: [[0.33639014]
 [0.37792434]]
b2: [[0.38564221]]
----------------------------------------
A2: [[3.54644581]]
****************************************
A0: [[7]
 [9]]
W1: [[0.22831673 0.31233823]
 [0.23558598 0.32510284]]
b1: [[0.02082502]
 [0.02204362]]
----------------------------------------
A1: [[3.73931597]
 [5.13433676]]
****************************************
A1: [[3.73931597]
 [5.13433676]]
W2: [[0.3397372 ]
 [0.38253181]]
b2: [[0.38343892]]
----------------------------------------
A2: [[3.61787081]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.23509059 0.32104747]
 [0.24326252 0.33497268]]
b1: [[0.02179271]
 [0.02314027]]
----------------------------------------
A1: [[3.86496148]
 [5.2991519 ]]
****************************************
A1: [[3.86496148]
 [5.2991519 ]]
W2: [[0.35007363]
 [0.39672445]]
b2: [[0.39948871]]
----------------------------------------
A2: [[3.85481293]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.24452913 0.33677838]
 [0.25406036 0.35296907]]
b1: [[0.02336581]
 [0.02493991]]
----------------------------------------
A1: [[4.29473577]
 [5.94446068]]
****************************************
A1: [[4.29473577]
 [5.94446068]]
W2: [[0.36665576]
 [0.41945979]]
b2: [[0.42375017]]
----------------------------------------
A2: [[4.49190204]]
****************************************
epoch - 4 loss 3.252093863403161
A0: [[8]
 [8]]
W1: [[0.25426555 0.36014576]
 [0.2653287  0.38001309]]
b1: [[0.02531309]
 [0.02719358]]
----------------------------------------
A1: [[4.18206705]
 [5.94846444]]
****************************************
A1: [[4.18206705]
 [5.94846444]]
W2: [[0.388199  ]
 [0.44927837]]
b2: [[0.45429457]]
----------------------------------------
A2: [[4.75028523]]
****************************************
A0: [[7]
 [9]]
W1: [[0.24968072 0.35556094]
 [0.26004246 0.37472686]]
b1: [[0.02473998]
 [0.0265328 ]]
----------------------------------------
A1: [[4.11288719]
 [5.88800108]]
****************************************
A1: [[4.11288719]
 [5.88800108]]
W2: [[0.38192351]
 [0.44035228]]
b2: [[0.43885171]]
----------------------------------------
A2: [[4.60245475]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.25182457 0.35831731]
 [0.26251936 0.37791144]]
b1: [[0.02504625]
 [0.02688664]]
----------------------------------------
A1: [[4.16118723]
 [5.95590488]]
****************************************
A1: [[4.16118723]
 [5.95590488]]
W2: [[0.38519363]
 [0.44503378]]
b2: [[0.44582887]]
----------------------------------------
A2: [[4.69927052]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.25800593 0.36861958]
 [0.26970762 0.38989188]]
b1: [[0.02607647]
 [0.02808469]]
----------------------------------------
A1: [[4.55259758]
 [6.54988512]]
****************************************
A1: [[4.55259758]
 [6.54988512]]
W2: [[0.39601879]
 [0.46052782]]
b2: [[0.46312928]]
----------------------------------------
A2: [[5.28244776]]
****************************************
epoch - 5 loss 1.3407132589299964
A0: [[8]
 [8]]
W1: [[0.26507636 0.38558861]
 [0.27800387 0.40980287]]
b1: [[0.02749056]
 [0.02974394]]
----------------------------------------
A1: [[4.37213239]
 [6.39287582]]
****************************************
A1: [[4.37213239]
 [6.39287582]]
W2: [[0.41165744]
 [0.48302736]]
b2: [[0.48646246]]
----------------------------------------
A2: [[5.37421719]]
****************************************
A0: [[7]
 [9]]
W1: [[0.25628926 0.37680152]
 [0.26776965 0.39956865]]
b1: [[0.02639217]
 [0.02846466]]
----------------------------------------
A1: [[4.23034384]
 [6.26219313]]
****************************************
A1: [[4.23034384]
 [6.26219313]]
W2: [[0.39964092]
 [0.46545696]]
b2: [[0.46270852]]
----------------------------------------
A2: [[5.06810838]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.25590875 0.37631229]
 [0.26732664 0.39899907]]
b1: [[0.02633781]
 [0.02840137]]
----------------------------------------
A1: [[4.23505669]
 [6.27626575]]
****************************************
A1: [[4.23505669]
 [6.27626575]]
W2: [[0.39906468]
 [0.46460394]]
b2: [[0.46446773]]
----------------------------------------
A2: [[5.07050706]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.2604477  0.3838772 ]
 [0.27263893 0.40785289]]
b1: [[0.02709431]
 [0.02928675]]
----------------------------------------
A1: [[4.60099995]
 [6.84290737]]
****************************************
A1: [[4.60099995]
 [6.84290737]]
W2: [[0.40693759]
 [0.47627143]]
b2: [[0.47813042]]
----------------------------------------
A2: [[5.60953151]]
****************************************
epoch - 6 loss 1.1726178458115704
A0: [[8]
 [8]]
W1: [[0.26628395 0.3978842 ]
 [0.27952594 0.4243817 ]]
b1: [[0.02826156]
 [0.03066415]]
----------------------------------------
A1: [[4.39474062]
 [6.60879135]]
****************************************
A1: [[4.39474062]
 [6.60879135]]
W2: [[0.41973268]
 [0.49530113]]
b2: [[0.49808206]]
----------------------------------------
A2: [[5.6160401]]
****************************************
A0: [[7]
 [9]]
W1: [[0.25579834 0.38739859]
 [0.26727141 0.41212718]]
b1: [[0.02695086]
 [0.02913234]]
----------------------------------------
A1: [[4.22298197]
 [6.45006709]]
****************************************
A1: [[4.22298197]
 [6.45006709]]
W2: [[0.40552852]
 [0.47394098]]
b2: [[0.4707089]]
----------------------------------------
A2: [[5.24019967]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.25444145 0.38565402]
 [0.26568807 0.41009145]]
b1: [[0.02675701]
 [0.02890615]]
----------------------------------------
A1: [[4.21028641]
 [6.44374476]]
****************************************
A1: [[4.21028641]
 [6.44374476]]
W2: [[0.4034998 ]
 [0.47084237]]
b2: [[0.47036197]]
----------------------------------------
A2: [[5.2031998]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.25836371 0.39219112]
 [0.27028826 0.41775844]]
b1: [[0.02741072]
 [0.02967284]]
----------------------------------------
A1: [[4.56268841]
 [7.00372968]]
****************************************
A1: [[4.56268841]
 [7.00372968]]
W2: [[0.41020932]
 [0.48111113]]
b2: [[0.48270473]]
----------------------------------------
A2: [[5.72393432]]
****************************************
epoch - 7 loss 1.2331289135532644
A0: [[8]
 [8]]
W1: [[0.26374684 0.40511064]
 [0.27665564 0.43304016]]
b1: [[0.02848735]
 [0.03094632]]
----------------------------------------
A1: [[4.35170726]
 [6.73615269]]
****************************************
A1: [[4.35170726]
 [6.73615269]]
W2: [[0.4218539 ]
 [0.49898557]]
b2: [[0.5015377]]
----------------------------------------
A2: [[5.69856534]]
****************************************
A0: [[7]
 [9]]
W1: [[0.25268387 0.39404766]
 [0.2637166  0.42010111]]
b1: [[0.02710448]
 [0.02932894]]
----------------------------------------
A1: [[4.16934096]
 [6.56857259]]
****************************************
A1: [[4.16934096]
 [6.56857259]]
W2: [[0.40707058]
 [0.47610198]]
b2: [[0.47270484]]
----------------------------------------
A2: [[5.29723128]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.25100027 0.39188303]
 [0.26175167 0.41757478]]
b1: [[0.02686396]
 [0.02904824]]
----------------------------------------
A1: [[4.1503823 ]
 [6.55609421]]
****************************************
A1: [[4.1503823 ]
 [6.55609421]]
W2: [[0.40459206]
 [0.4721972 ]]
b2: [[0.47160274]]
----------------------------------------
A2: [[5.24658385]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.25471472 0.39807379]
 [0.26611012 0.42483886]]
b1: [[0.02748304]
 [0.02977465]]
----------------------------------------
A1: [[4.49437811]
 [7.1182099 ]]
****************************************
A1: [[4.49437811]
 [7.1182099 ]]
W2: [[0.41084599]
 [0.48207614]]
b2: [[0.48358297]]
----------------------------------------
A2: [[5.76159936]]
****************************************
epoch - 8 loss 1.2686856723180784
A0: [[8]
 [8]]
W1: [[0.2599405  0.41061565]
 [0.27229849 0.43969094]]
b1: [[0.02852819]
 [0.03101232]]
----------------------------------------
A1: [[4.28644008]
 [6.83346506]]
****************************************
A1: [[4.28644008]
 [6.83346506]]
W2: [[0.42197768]
 [0.49970653]]
b2: [[0.50218333]]
----------------------------------------
A2: [[5.72569247]]
****************************************
A0: [[7]
 [9]]
W1: [[0.24869772 0.39937287]
 [0.25915226 0.42654471]]
b1: [[0.02712285]
 [0.02936904]]
----------------------------------------
A1: [[4.10037721]
 [6.66388155]]
****************************************
A1: [[4.10037721]
 [6.66388155]]
W2: [[0.40718352]
 [0.47612161]]
b2: [[0.47267023]]
----------------------------------------
A2: [[5.31509429]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.2469129  0.39707811]
 [0.25707046 0.42386811]]
b1: [[0.02686787]
 [0.02907164]]
----------------------------------------
A1: [[4.07904988]
 [6.65022141]]
****************************************
A1: [[4.07904988]
 [6.65022141]]
W2: [[0.40459951]
 [0.47192211]]
b2: [[0.47129192]]
----------------------------------------
A2: [[5.26006002]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.25055905 0.40315503]
 [0.26134817 0.43099764]]
b1: [[0.02747557]
 [0.02978459]]
----------------------------------------
A1: [[4.41644892]
 [7.21753136]]
****************************************
A1: [[4.41644892]
 [7.21753136]]
W2: [[0.41063601]
 [0.48176364]]
b2: [[0.48324352]]
----------------------------------------
A2: [[5.77394067]]
****************************************
epoch - 9 loss 1.282007891421992
A0: [[8]
 [8]]
W1: [[0.25572647 0.41555683]
 [0.26747187 0.44569451]]
b1: [[0.02850905]
 [0.03100933]]
----------------------------------------
A1: [[4.21409581]
 [6.9210201 ]]
****************************************
A1: [[4.21409581]
 [6.9210201 ]]
W2: [[0.42146567]
 [0.49946188]]
b2: [[0.501914]]
----------------------------------------
A2: [[5.73479645]]
****************************************
A0: [[7]
 [9]]
W1: [[0.24443379 0.40426416]
 [0.25427496 0.4324976 ]]
b1: [[0.02709746]
 [0.02935972]]
----------------------------------------
A1: [[4.0266087 ]
 [6.75168725]]
****************************************
A1: [[4.0266087 ]
 [6.75168725]]
W2: [[0.40684447]
 [0.47544876]]
b2: [[0.47197917]]
----------------------------------------
A2: [[5.320264]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.24262119 0.40193367]
 [0.25216259 0.42978169]]
b1: [[0.02683852]
 [0.02905795]]
----------------------------------------
A1: [[4.00419153]
 [6.73847685]]
****************************************
A1: [[4.00419153]
 [6.73847685]]
W2: [[0.40426532]
 [0.47112412]]
b2: [[0.47048359]]
----------------------------------------
A2: [[5.2638983]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.24624423 0.40797206]
 [0.25641176 0.43686364]]
b1: [[0.02744236]
 [0.02976615]]
----------------------------------------
A1: [[4.3356046 ]
 [7.31199018]]
****************************************
A1: [[4.3356046 ]
 [7.31199018]]
W2: [[0.4101603 ]
 [0.48104452]]
b2: [[0.48251673]]
----------------------------------------
A2: [[5.77820246]]
****************************************
epoch - 10 loss 1.286680671174487
A0: [[8]
 [8]]
W1: [[0.251385   0.42030991]
 [0.26250745 0.45149331]]
b1: [[0.02847052]
 [0.03098528]]
----------------------------------------
A1: [[4.13961014]
 [7.00541108]]
****************************************
A1: [[4.13961014]
 [7.00541108]]
W2: [[0.42075476]
 [0.49891207]]
b2: [[0.50135566]]
----------------------------------------
A2: [[5.73820048]]
****************************************
A0: [[7]
 [9]]
W1: [[0.24008353 0.40900844]
 [0.24930941 0.43829527]]
b1: [[0.02705783]
 [0.02933553]]
----------------------------------------
A1: [[3.95142724]
 [6.83705206]]
****************************************
A1: [[3.95142724]
 [6.83705206]]
W2: [[0.40636382]
 [0.47455845]]
b2: [[0.47108205]]
----------------------------------------
A2: [[5.32137994]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.2382666  0.40667239]
 [0.24719399 0.43557545]]
b1: [[0.02679827]
 [0.02903333]]
----------------------------------------
A1: [[3.92833779]
 [6.82482212]]
****************************************
A1: [[3.92833779]
 [6.82482212]]
W2: [[0.403824  ]
 [0.47016387]]
b2: [[0.46952111]]
----------------------------------------
A2: [[5.26466295]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.24188094 0.41269629]
 [0.25143131 0.44263764]]
b1: [[0.02740066]
 [0.02973955]]
----------------------------------------
A1: [[4.25398104]
 [7.40487264]]
****************************************
A1: [[4.25398104]
 [7.40487264]]
W2: [[0.40960131]
 [0.48020096]]
b2: [[0.48167163]]
----------------------------------------
A2: [[5.77993474]]
****************************************
epoch - 11 loss 1.288476448757492
A0: [[8]
 [8]]
W1: [[0.24700499 0.424994  ]
 [0.25751052 0.45722776]]
b1: [[0.02842547]
 [0.03095539]]
----------------------------------------
A1: [[4.06454956]
 [7.0887295 ]]
****************************************
A1: [[4.06454956]
 [7.0887295 ]]
W2: [[0.41998157]
 [0.49826981]]
b2: [[0.50070994]]
----------------------------------------
A2: [[5.73984578]]
****************************************
A0: [[7]
 [9]]
W1: [[0.23570745 0.41369647]
 [0.24432658 0.44404381]]
b1: [[0.02701328]
 [0.0293074 ]]
----------------------------------------
A1: [[3.87590467]
 [6.92157702]]
****************************************
A1: [[3.87590467]
 [6.92157702]]
W2: [[0.4058382 ]
 [0.47360322]]
b2: [[0.47012353]]
----------------------------------------
A2: [[5.32119485]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.23389371 0.41136451]
 [0.24221691 0.44133138]]
b1: [[0.02675417]
 [0.02900601]]
----------------------------------------
A1: [[3.85228549]
 [6.91050687]]
****************************************
A1: [[3.85228549]
 [6.91050687]]
W2: [[0.40334835]
 [0.46915687]]
b2: [[0.46851448]]
----------------------------------------
A2: [[5.26443927]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.23750397 0.41738162]
 [0.24644776 0.4483828 ]]
b1: [[0.02735588]
 [0.02971116]]
----------------------------------------
A1: [[4.17224892]
 [7.49721293]]
****************************************
A1: [[4.17224892]
 [7.49721293]]
W2: [[0.40901553]
 [0.47932307]]
b2: [[0.48079419]]
----------------------------------------
A2: [[5.78089589]]
****************************************
epoch - 12 loss 1.2893734737446352
A0: [[8]
 [8]]
W1: [[0.24261432 0.42964645]
 [0.25251406 0.46294192]]
b1: [[0.02837795]
 [0.03092442]]
----------------------------------------
A1: [[3.98940497]
 [7.17163132]]
****************************************
A1: [[3.98940497]
 [7.17163132]]
W2: [[0.41918835]

{'W1': array([[-0.14103574,  0.77430121],
        [-0.13553895,  0.95855198]]),
 'b1': array([[0.02109149],
        [0.03169597]]),
 'W2': array([[0.35895682],
        [0.45330172]]),
 'b2': array([[0.45531158]])}

In [15]:
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From C:\Users\shiva\AppData\Roaming\Python\Python311\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [16]:
model = Sequential()
model.add(Dense(2,activation = "linear" , input_dim = 2))
model.add(Dense(1 , activation = "linear"))

WARNING:tensorflow:From C:\Users\shiva\AppData\Roaming\Python\Python311\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 2)                 6

 dense_1 (Dense)             (None, 1)                 3

=================================================================
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
model.compile(loss = "mean_squared_error" ,optimizer = "adam" )

WARNING:tensorflow:From C:\Users\shiva\AppData\Roaming\Python\Python311\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [19]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [20]:
model.fit(df.iloc[:,0:-1].values , df.lpa.values ,epochs = 75 , verbose = 1 , batch_size =  1)

Epoch 1/75
WARNING:tensorflow:From C:\Users\shiva\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

4/4 [==============================] - 1s 5ms/step - loss: 12.9420
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 12.2219
Epoch 3/75
4/4 [==============================] - 0s 2ms/step - loss: 11.5787
Epoch 4/75
4/4 [==============================] - 0s 1ms/step - loss: 10.9481
Epoch 5/75
4/4 [==============================] - 0s 2ms/step - loss: 10.1977
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 9.6796
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 9.0156
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 8.5145
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 8.0733
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 7.6446
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 7.1574
Epoch 12/75
4/4 [==============================] - 0s 5ms/step - loss: 6.8387
Epoch 13/75
4/4 [==============================] - 0s 4ms/step - loss: 6.4012
Epoch 14/75
4/4 [==============================] - 0s 3ms/step - loss: 6.0369
Epoch 15/75
4/4 [==============================] - 0s 4ms/step - loss: 5.7348
Epoch 16/75
4/4 [==============================] - 0s 4ms/step - loss: 5.5317
Epoch 17/75
4/4 [==============================] - 0s 2ms/step - loss: 5.1605
Epoch 18/75
4/4 [==============================] - 0s 4ms/step - loss: 4.9259
Epoch 19/75
4/4 [==============================] - 0s 3ms/step - loss: 4.6886
Epoch 20/75
4/4 [==============================] - 0s 3ms/step - loss: 4.5011
Epoch 21/75
4/4 [==============================] - 0s 4ms/step - loss: 4.2357
Epoch 22/75
4/4 [==============================] - 0s 3ms/step - loss: 4.1045
Epoch 23/75
4/4 [==============================] - 0s 3ms/step - loss: 3.9203
Epoch 24/75
4/4 [==============================] - 0s 3ms/step - loss: 3.7369
Epoch 25/75
4/4 [==============================] - 0s 715us/step - loss: 3.5627
Epoch 26/75
4/4 [==============================] - 0s 3ms/step - loss: 3.4502
Epoch 27/75
4/4 [==============================] - 0s 2ms/step - loss: 3.3304
Epoch 28/75
4/4 [==============================] - 0s 3ms/step - loss: 3.1992
Epoch 29/75
4/4 [==============================] - 0s 2ms/step - loss: 3.1261
Epoch 30/75
4/4 [==============================] - 0s 5ms/step - loss: 2.9781
Epoch 31/75
4/4 [==============================] - 0s 4ms/step - loss: 2.8994
Epoch 32/75
4/4 [==============================] - 0s 4ms/step - loss: 2.8163
Epoch 33/75
4/4 [==============================] - 0s 2ms/step - loss: 2.7138
Epoch 34/75
4/4 [==============================] - 0s 4ms/step - loss: 2.6652
Epoch 35/75
4/4 [==============================] - 0s 3ms/step - loss: 2.5933
Epoch 36/75
4/4 [==============================] - 0s 5ms/step - loss: 2.5109
Epoch 37/75
4/4 [==============================] - 0s 3ms/step - loss: 2.4432
Epoch 38/75
4/4 [==============================] - 0s 6ms/step - loss: 2.3895
Epoch 39/75
4/4 [==============================] - 0s 2ms/step - loss: 2.3339
Epoch 40/75
4/4 [==============================] - 0s 2ms/step - loss: 2.2988
Epoch 41/75
4/4 [==============================] - 0s 4ms/step - loss: 2.2323
Epoch 42/75
4/4 [==============================] - 0s 4ms/step - loss: 2.2253
Epoch 43/75
4/4 [==============================] - 0s 4ms/step - loss: 2.1629
Epoch 44/75
4/4 [==============================] - 0s 3ms/step - loss: 2.1397
Epoch 45/75
4/4 [==============================] - 0s 454us/step - loss: 2.0819
Epoch 46/75
4/4 [==============================] - 0s 3ms/step - loss: 2.0456
Epoch 47/75
4/4 [==============================] - 0s 3ms/step - loss: 2.0437
Epoch 48/75
4/4 [==============================] - 0s 2ms/step - loss: 1.9997
Epoch 49/75
4/4 [==============================] - 0s 3ms/step - loss: 1.9710
Epoch 50/75
4/4 [==============================] - 0s 3ms/step - loss: 1.9463
Epoch 51/75
4/4 [==============================] - 0s 3ms/step - loss: 1.9204
Epoch 52/75
4/4 [==============================] - 0s 4ms/step - loss: 1.8909
Epoch 53/75
4/4 [==============================] - 0s 4ms/step - loss: 1.8640
Epoch 54/75
4/4 [==============================] - 0s 4ms/step - loss: 1.8553
Epoch 55/75
4/4 [==============================] - 0s 2ms/step - loss: 1.8243
Epoch 56/75
4/4 [==============================] - 0s 2ms/step - loss: 1.8113
Epoch 57/75
4/4 [==============================] - 0s 1ms/step - loss: 1.7887
Epoch 58/75
4/4 [==============================] - 0s 4ms/step - loss: 1.7783
Epoch 59/75
4/4 [==============================] - 0s 3ms/step - loss: 1.7606
Epoch 60/75
4/4 [==============================] - 0s 5ms/step - loss: 1.7374
Epoch 61/75
4/4 [==============================] - 0s 4ms/step - loss: 1.7323
Epoch 62/75
4/4 [==============================] - 0s 3ms/step - loss: 1.7079
Epoch 63/75
4/4 [==============================] - 0s 3ms/step - loss: 1.6970
Epoch 64/75
4/4 [==============================] - 0s 2ms/step - loss: 1.6871
Epoch 65/75
4/4 [==============================] - 0s 3ms/step - loss: 1.6660
Epoch 66/75
4/4 [==============================] - 0s 3ms/step - loss: 1.6555
Epoch 67/75
4/4 [==============================] - 0s 3ms/step - loss: 1.6403
Epoch 68/75
4/4 [==============================] - 0s 2ms/step - loss: 1.6298
Epoch 69/75
4/4 [==============================] - 0s 3ms/step - loss: 1.6135
Epoch 70/75
4/4 [==============================] - 0s 3ms/step - loss: 1.6019
Epoch 71/75
4/4 [==============================] - 0s 3ms/step - loss: 1.5898
Epoch 72/75
4/4 [==============================] - 0s 3ms/step - loss: 1.5789
Epoch 73/75
4/4 [==============================] - 0s 5ms/step - loss: 1.5686
Epoch 74/75
4/4 [==============================] - 0s 3ms/step - loss: 1.5599
Epoch 75/75
4/4 [==============================] - 0s 3ms/step - loss: 1.5446