In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = {"cgpa":[7,8,9,8,6,5],
       "iq": [90,60,80,102,89,45],
        "resume score" :[80,60,50,70,90,87],
       "package":[9,7,8,9,6,7]}

In [3]:
df = pd.DataFrame(data)
df

   cgpa   iq  resume score  package
0     7   90            80        9
1     8   60            60        7
2     9   80            50        8
3     8  102            70        9
4     6   89            90        6
5     5   45            87        7

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x= df.drop(columns = "package")
y = df.package

In [6]:
x_train , x_test , y_train , y_test = train_test_split(x ,y , test_size = 0.2 , random_state = 1)

In [7]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From C:\Users\shiva\AppData\Roaming\Python\Python311\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [8]:
model = Sequential()

model.add(Dense(6, activation = "relu" , input_dim = 3))
model.add(Dense(1 , activation = "linear"))

WARNING:tensorflow:From C:\Users\shiva\AppData\Roaming\Python\Python311\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 6)                 24

 dense_1 (Dense)             (None, 1)                 7

=================================================================
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [10]:
model.compile(loss = "mean_squared_error" , optimizer = "adam")

WARNING:tensorflow:From C:\Users\shiva\AppData\Roaming\Python\Python311\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [ ]:
model.fit(x_train , y_train , epochs = 3500)

Epoch 1/3500
WARNING:tensorflow:From C:\Users\shiva\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

1/1 [==============================] - 1s 884ms/step - loss: 134.3418
Epoch 2/3500
1/1 [==============================] - 0s 33ms/step - loss: 131.7654
Epoch 3/3500
1/1 [==============================] - 0s 0s/step - loss: 129.2254
Epoch 4/3500
1/1 [==============================] - 0s 8ms/step - loss: 126.7222
Epoch 5/3500
1/1 [==============================] - 0s 5ms/step - loss: 124.2564
Epoch 6/3500
1/1 [==============================] - 0s 5ms/step - loss: 122.1269
Epoch 7/3500
1/1 [==============================] - 0s 0s/step - loss: 120.2953
Epoch 8/3500
1/1 [==============================] - 0s 6ms/step - loss: 118.4793
Epoch 9/3500
1/1 [==============================] - 0s 9ms/step - loss: 116.6814
Epoch 10/3500
1/1 [==============================] - 0s 6ms/step - loss: 114.9038
Epoch 11/3500
1/1 [==============================] - 0s 9ms/step - loss: 113.1486
Epoch 12/3500
1/1 [==============================] - 0s 0s/step - loss: 111.4172
Epoch 13/3500
1/1 [==============================] - 0s 0s/step - loss: 109.7107
Epoch 14/3500
1/1 [==============================] - 0s 3ms/step - loss: 108.0302
Epoch 15/3500
1/1 [==============================] - 0s 4ms/step - loss: 106.3760
Epoch 16/3500
1/1 [==============================] - 0s 9ms/step - loss: 104.7485
Epoch 17/3500
1/1 [==============================] - 0s 2ms/step - loss: 103.1475
Epoch 18/3500
1/1 [==============================] - 0s 3ms/step - loss: 101.5728
Epoch 19/3500
1/1 [==============================] - 0s 5ms/step - loss: 100.0239
Epoch 20/3500
1/1 [==============================] - 0s 9ms/step - loss: 98.5001
Epoch 21/3500
1/1 [==============================] - 0s 7ms/step - loss: 97.0007
Epoch 22/3500
1/1 [==============================] - 0s 8ms/step - loss: 95.5250
Epoch 23/3500
1/1 [==============================] - 0s 6ms/step - loss: 94.0724
Epoch 24/3500
1/1 [==============================] - 0s 9ms/step - loss: 92.6423
Epoch 25/3500
1/1 [==============================] - 0s 7ms/step - loss: 91.2340
Epoch 26/3500
1/1 [==============================] - 0s 4ms/step - loss: 89.8473
Epoch 27/3500
1/1 [==============================] - 0s 11ms/step - loss: 88.4818
Epoch 28/3500
1/1 [==============================] - 0s 0s/step - loss: 87.1374
Epoch 29/3500
1/1 [==============================] - 0s 15ms/step - loss: 85.8137
Epoch 30/3500
1/1 [==============================] - 0s 0s/step - loss: 84.5104
Epoch 31/3500
1/1 [==============================] - 0s 13ms/step - loss: 83.2276
Epoch 32/3500
1/1 [==============================] - 0s 4ms/step - loss: 81.9648
Epoch 33/3500
1/1 [==============================] - 0s 11ms/step - loss: 80.7218
Epoch 34/3500
1/1 [==============================] - 0s 4ms/step - loss: 79.4982
Epoch 35/3500
1/1 [==============================] - 0s 8ms/step - loss: 78.2937
Epoch 36/3500
1/1 [==============================] - 0s 2ms/step - loss: 77.1079
Epoch 37/3500
1/1 [==============================] - 0s 3ms/step - loss: 75.9403
Epoch 38/3500
1/1 [==============================] - 0s 5ms/step - loss: 74.7905
Epoch 39/3500
1/1 [==============================] - 0s 0s/step - loss: 73.6580
Epoch 40/3500
1/1 [==============================] - 0s 12ms/step - loss: 72.5425
Epoch 41/3500
1/1 [==============================] - 0s 5ms/step - loss: 71.4435
Epoch 42/3500
1/1 [==============================] - 0s 6ms/step - loss: 70.3606
Epoch 43/3500
1/1 [==============================] - 0s 6ms/step - loss: 69.2936
Epoch 44/3500
1/1 [==============================] - 0s 10ms/step - loss: 68.2420
Epoch 45/3500
1/1 [==============================] - 0s 7ms/step - loss: 67.2056
Epoch 46/3500
1/1 [==============================] - 0s 34ms/step - loss: 66.3170
Epoch 47/3500
1/1 [==============================] - 0s 0s/step - loss: 65.3942
Epoch 48/3500
1/1 [==============================] - 0s 13ms/step - loss: 64.4281
Epoch 49/3500
1/1 [==============================] - 0s 0s/step - loss: 63.4287
Epoch 50/3500
1/1 [==============================] - 0s 17ms/step - loss: 62.4355
Epoch 51/3500
1/1 [==============================] - 0s 6ms/step - loss: 61.5541
Epoch 52/3500
1/1 [==============================] - 0s 0s/step - loss: 60.6799
Epoch 53/3500
1/1 [==============================] - 0s 2ms/step - loss: 59.8120
Epoch 54/3500
1/1 [==============================] - 0s 0s/step - loss: 58.9503
Epoch 55/3500
1/1 [==============================] - 0s 3ms/step - loss: 58.0948
Epoch 56/3500
1/1 [==============================] - 0s 10ms/step - loss: 57.2461
Epoch 57/3500
1/1 [==============================] - 0s 11ms/step - loss: 56.4046
Epoch 58/3500
1/1 [==============================] - 0s 4ms/step - loss: 55.5712
Epoch 59/3500
1/1 [==============================] - 0s 8ms/step - loss: 54.7464
Epoch 60/3500
1/1 [==============================] - 0s 0s/step - loss: 53.9818
Epoch 61/3500
1/1 [==============================] - 0s 7ms/step - loss: 53.2160
Epoch 62/3500
1/1 [==============================] - 0s 5ms/step - loss: 52.4185
Epoch 63/3500
1/1 [==============================] - 0s 0s/step - loss: 51.6516
Epoch 64/3500
1/1 [==============================] - 0s 0s/step - loss: 50.9210
Epoch 65/3500
1/1 [==============================] - 0s 8ms/step - loss: 50.1944
Epoch 66/3500
1/1 [==============================] - 0s 0s/step - loss: 49.4724
Epoch 67/3500
1/1 [==============================] - 0s 0s/step - loss: 48.7553
Epoch 68/3500
1/1 [==============================] - 0s 12ms/step - loss: 48.0437
Epoch 69/3500
1/1 [==============================] - 0s 6ms/step - loss: 47.3379
Epoch 70/3500
1/1 [==============================] - 0s 0s/step - loss: 46.6384
Epoch 71/3500
1/1 [==============================] - 0s 177us/step - loss: 45.9657
Epoch 72/3500
1/1 [==============================] - 0s 8ms/step - loss: 45.3031
Epoch 73/3500
1/1 [==============================] - 0s 0s/step - loss: 44.6308
Epoch 74/3500
1/1 [==============================] - 0s 8ms/step - loss: 43.9881
Epoch 75/3500
1/1 [==============================] - 0s 8ms/step - loss: 43.3494
Epoch 76/3500
1/1 [==============================] - 0s 3ms/step - loss: 42.7149
Epoch 77/3500
1/1 [==============================] - 0s 5ms/step - loss: 42.0852
Epoch 78/3500
1/1 [==============================] - 0s 8ms/step - loss: 41.4952
Epoch 79/3500
1/1 [==============================] - 0s 0s/step - loss: 40.8819
Epoch 80/3500
1/1 [==============================] - 0s 8ms/step - loss: 40.2748
Epoch 81/3500
1/1 [==============================] - 0s 8ms/step - loss: 39.6948
Epoch 82/3500
1/1 [==============================] - 0s 6ms/step - loss: 39.1175
Epoch 83/3500
1/1 [==============================] - 0s 0s/step - loss: 38.5432
Epoch 84/3500
1/1 [==============================] - 0s 9ms/step - loss: 37.9723
Epoch 85/3500
1/1 [==============================] - 0s 5ms/step - loss: 37.4052
Epoch 86/3500
1/1 [==============================] - 0s 5ms/step - loss: 36.8709
Epoch 87/3500
1/1 [==============================] - 0s 0s/step - loss: 36.3272
Epoch 88/3500
1/1 [==============================] - 0s 11ms/step - loss: 35.7766
Epoch 89/3500
1/1 [==============================] - 0s 0s/step - loss: 35.2549
Epoch 90/3500
1/1 [==============================] - 0s 9ms/step - loss: 34.7355
Epoch 91/3500
1/1 [==============================] - 0s 6ms/step - loss: 34.2187
Epoch 92/3500
1/1 [==============================] - 0s 4ms/step - loss: 33.7051
Epoch 93/3500
1/1 [==============================] - 0s 5ms/step - loss: 33.2233
Epoch 94/3500
1/1 [==============================] - 0s 0s/step - loss: 32.7253
Epoch 95/3500
1/1 [==============================] - 0s 4ms/step - loss: 32.2296
Epoch 96/3500
1/1 [==============================] - 0s 4ms/step - loss: 31.7568
Epoch 97/3500
1/1 [==============================] - 0s 5ms/step - loss: 31.2859
Epoch 98/3500
1/1 [==============================] - 0s 2ms/step - loss: 30.8173
Epoch 99/3500
1/1 [==============================] - 0s 0s/step - loss: 30.3513
Epoch 100/3500
1/1 [==============================] - 0s 8ms/step - loss: 29.8899
Epoch 101/3500
1/1 [==============================] - 0s 4ms/step - loss: 29.4431
Epoch 102/3500
1/1 [==============================] - 0s 5ms/step - loss: 28.9999
Epoch 103/3500
1/1 [==============================] - 0s 4ms/step - loss: 28.5757
Epoch 104/3500
1/1 [==============================] - 0s 5ms/step - loss: 28.1349
Epoch 105/3500
1/1 [==============================] - 0s 8ms/step - loss: 27.7123
Epoch 106/3500
1/1 [==============================] - 0s 8ms/step - loss: 27.2933
Epoch 107/3500
1/1 [==============================] - 0s 0s/step - loss: 26.8872
Epoch 108/3500
1/1 [==============================] - 0s 12ms/step - loss: 26.4838
Epoch 109/3500
1/1 [==============================] - 0s 5ms/step - loss: 26.0824
Epoch 110/3500
1/1 [==============================] - 0s 5ms/step - loss: 25.6833
Epoch 111/3500
1/1 [==============================] - 0s 4ms/step - loss: 25.2913
Epoch 112/3500
1/1 [==============================] - 0s 3ms/step - loss: 24.9055
Epoch 113/3500
1/1 [==============================] - 0s 0s/step - loss: 24.5259
Epoch 114/3500
1/1 [==============================] - 0s 8ms/step - loss: 24.1583
Epoch 115/3500
1/1 [==============================] - 0s 655us/step - loss: 23.7853
Epoch 116/3500
1/1 [==============================] - 0s 4ms/step - loss: 23.4236
Epoch 117/3500
1/1 [==============================] - 0s 4ms/step - loss: 23.0639
Epoch 118/3500
1/1 [==============================] - 0s 4ms/step - loss: 22.7135
Epoch 119/3500
1/1 [==============================] - 0s 6ms/step - loss: 22.3624
Epoch 120/3500
1/1 [==============================] - 0s 0s/step - loss: 22.0200
Epoch 121/3500
1/1 [==============================] - 0s 10ms/step - loss: 21.6795
Epoch 122/3500
1/1 [==============================] - 0s 3ms/step - loss: 21.3559
Epoch 123/3500
1/1 [==============================] - 0s 5ms/step - loss: 21.0181
Epoch 124/3500
1/1 [==============================] - 0s 7ms/step - loss: 20.7023
Epoch 125/3500
1/1 [==============================] - 0s 3ms/step - loss: 20.3896
Epoch 126/3500
1/1 [==============================] - 0s 4ms/step - loss: 20.0778
Epoch 127/3500
1/1 [==============================] - 0s 0s/step - loss: 19.7674
Epoch 128/3500
1/1 [==============================] - 0s 3ms/step - loss: 19.4586
Epoch 129/3500
1/1 [==============================] - 0s 5ms/step - loss: 19.1518
Epoch 130/3500
1/1 [==============================] - 0s 4ms/step - loss: 18.8476
Epoch 131/3500
1/1 [==============================] - 0s 5ms/step - loss: 18.5619
Epoch 132/3500
1/1 [==============================] - 0s 5ms/step - loss: 18.2759
Epoch 133/3500
1/1 [==============================] - 0s 10ms/step - loss: 17.9780
Epoch 134/3500
1/1 [==============================] - 0s 6ms/step - loss: 17.7006
Epoch 135/3500
1/1 [==============================] - 0s 0s/step - loss: 17.4247
Epoch 136/3500
1/1 [==============================] - 0s 0s/step - loss: 17.1506
Epoch 137/3500
1/1 [==============================] - 0s 8ms/step - loss: 16.8865
Epoch 138/3500
1/1 [==============================] - 0s 3ms/step - loss: 16.6170
Epoch 139/3500
1/1 [==============================] - 0s 2ms/step - loss: 16.3569
Epoch 140/3500
1/1 [==============================] - 0s 8ms/step - loss: 16.1027
Epoch 141/3500
1/1 [==============================] - 0s 0s/step - loss: 15.8502
Epoch 142/3500
1/1 [==============================] - 0s 9ms/step - loss: 15.6031
Epoch 143/3500
1/1 [==============================] - 0s 0s/step - loss: 15.3574
Epoch 144/3500
1/1 [==============================] - 0s 0s/step - loss: 15.1133
Epoch 145/3500
1/1 [==============================] - 0s 8ms/step - loss: 14.8808
Epoch 146/3500
1/1 [==============================] - 0s 0s/step - loss: 14.6416
Epoch 147/3500
1/1 [==============================] - 0s 8ms/step - loss: 14.4150
Epoch 148/3500
1/1 [==============================] - 0s 0s/step - loss: 14.1921
Epoch 149/3500
1/1 [==============================] - 0s 10ms/step - loss: 13.9702
Epoch 150/3500
1/1 [==============================] - 0s 7ms/step - loss: 13.7493
Epoch 151/3500
1/1 [==============================] - 0s 0s/step - loss: 13.5299
Epoch 152/3500
1/1 [==============================] - 0s 10ms/step - loss: 13.3120
Epoch 153/3500
1/1 [==============================] - 0s 7ms/step - loss: 13.0962
Epoch 154/3500
1/1 [==============================] - 0s 4ms/step - loss: 12.9043
Epoch 155/3500
1/1 [==============================] - 0s 4ms/step - loss: 12.7022
Epoch 156/3500
1/1 [==============================] - 0s 0s/step - loss: 12.4889
Epoch 157/3500
1/1 [==============================] - 0s 11ms/step - loss: 12.2917
Epoch 158/3500
1/1 [==============================] - 0s 7ms/step - loss: 12.1029
Epoch 159/3500
1/1 [==============================] - 0s 0s/step - loss: 11.9149
Epoch 160/3500
1/1 [==============================] - 0s 0s/step - loss: 11.7276
Epoch 161/3500
1/1 [==============================] - 0s 9ms/step - loss: 11.5413
Epoch 162/3500
1/1 [==============================] - 0s 0s/step - loss: 11.3562
Epoch 163/3500
1/1 [==============================] - 0s 11ms/step - loss: 11.1726
Epoch 164/3500
1/1 [==============================] - 0s 6ms/step - loss: 10.9908
Epoch 165/3500
1/1 [==============================] - 0s 0s/step - loss: 10.8110
Epoch 166/3500
1/1 [==============================] - 0s 0s/step - loss: 10.6495
Epoch 167/3500
1/1 [==============================] - 0s 9ms/step - loss: 10.4843
Epoch 168/3500
1/1 [==============================] - 0s 0s/step - loss: 10.3089
Epoch 169/3500
1/1 [==============================] - 0s 0s/step - loss: 10.1424
Epoch 170/3500
1/1 [==============================] - 0s 11ms/step - loss: 9.9860
Epoch 171/3500
1/1 [==============================] - 0s 6ms/step - loss: 9.8303
Epoch 172/3500
1/1 [==============================] - 0s 0s/step - loss: 9.6756
Epoch 173/3500
1/1 [==============================] - 0s 5ms/step - loss: 9.5218
Epoch 174/3500
1/1 [==============================] - 0s 0s/step - loss: 9.3691
Epoch 175/3500
1/1 [==============================] - 0s 11ms/step - loss: 9.2177
Epoch 176/3500
1/1 [==============================] - 0s 5ms/step - loss: 9.0678
Epoch 177/3500
1/1 [==============================] - 0s 5ms/step - loss: 8.9202
Epoch 178/3500
1/1 [==============================] - 0s 0s/step - loss: 8.7801
Epoch 179/3500
1/1 [==============================] - 0s 8ms/step - loss: 8.6418
Epoch 180/3500
1/1 [==============================] - 0s 8ms/step - loss: 8.5066
Epoch 181/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.3724
Epoch 182/3500
1/1 [==============================] - 0s 4ms/step - loss: 8.2392
Epoch 183/3500
1/1 [==============================] - 0s 29ms/step - loss: 8.1072
Epoch 184/3500
1/1 [==============================] - 0s 2ms/step - loss: 7.9810
Epoch 185/3500
1/1 [==============================] - 0s 10ms/step - loss: 7.8529
Epoch 186/3500
1/1 [==============================] - 0s 4ms/step - loss: 7.7316
Epoch 187/3500
1/1 [==============================] - 0s 1ms/step - loss: 7.6124
Epoch 188/3500
1/1 [==============================] - 0s 10ms/step - loss: 7.4938
Epoch 189/3500
1/1 [==============================] - 0s 6ms/step - loss: 7.3760
Epoch 190/3500
1/1 [==============================] - 0s 0s/step - loss: 7.2592
Epoch 191/3500
1/1 [==============================] - 0s 9ms/step - loss: 7.1435
Epoch 192/3500
1/1 [==============================] - 0s 6ms/step - loss: 7.0290
Epoch 193/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.9269
Epoch 194/3500
1/1 [==============================] - 0s 0s/step - loss: 6.8195
Epoch 195/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.7056
Epoch 196/3500
1/1 [==============================] - 0s 7ms/step - loss: 6.6048
Epoch 197/3500
1/1 [==============================] - 0s 0s/step - loss: 6.5059
Epoch 198/3500
1/1 [==============================] - 0s 12ms/step - loss: 6.4075
Epoch 199/3500
1/1 [==============================] - 0s 0s/step - loss: 6.3096
Epoch 200/3500
1/1 [==============================] - 0s 3ms/step - loss: 6.2123
Epoch 201/3500
1/1 [==============================] - 0s 8ms/step - loss: 6.1157
Epoch 202/3500
1/1 [==============================] - 0s 4ms/step - loss: 6.0200
Epoch 203/3500
1/1 [==============================] - 0s 0s/step - loss: 5.9254
Epoch 204/3500
1/1 [==============================] - 0s 12ms/step - loss: 5.8320
Epoch 205/3500
1/1 [==============================] - 0s 5ms/step - loss: 5.7399
Epoch 206/3500
1/1 [==============================] - 0s 0s/step - loss: 5.6616
Epoch 207/3500
1/1 [==============================] - 0s 2ms/step - loss: 5.5781
Epoch 208/3500
1/1 [==============================] - 0s 7ms/step - loss: 5.4885
Epoch 209/3500
1/1 [==============================] - 0s 0s/step - loss: 5.3999
Epoch 210/3500
1/1 [==============================] - 0s 10ms/step - loss: 5.3209
Epoch 211/3500
1/1 [==============================] - 0s 0s/step - loss: 5.2425
Epoch 212/3500
1/1 [==============================] - 0s 0s/step - loss: 5.1647
Epoch 213/3500
1/1 [==============================] - 0s 12ms/step - loss: 5.0875
Epoch 214/3500
1/1 [==============================] - 0s 4ms/step - loss: 5.0110
Epoch 215/3500
1/1 [==============================] - 0s 6ms/step - loss: 4.9353
Epoch 216/3500
1/1 [==============================] - 0s 0s/step - loss: 4.8604
Epoch 217/3500
1/1 [==============================] - 0s 6ms/step - loss: 4.7865
Epoch 218/3500
1/1 [==============================] - 0s 9ms/step - loss: 4.7227
Epoch 219/3500
1/1 [==============================] - 0s 4ms/step - loss: 4.6548
Epoch 220/3500
1/1 [==============================] - 0s 0s/step - loss: 4.5821
Epoch 221/3500
1/1 [==============================] - 0s 12ms/step - loss: 4.5142
Epoch 222/3500
1/1 [==============================] - 0s 6ms/step - loss: 4.4512
Epoch 223/3500
1/1 [==============================] - 0s 0s/step - loss: 4.3884
Epoch 224/3500
1/1 [==============================] - 0s 11ms/step - loss: 4.3261
Epoch 225/3500
1/1 [==============================] - 0s 6ms/step - loss: 4.2642
Epoch 226/3500
1/1 [==============================] - 0s 0s/step - loss: 4.2028
Epoch 227/3500
1/1 [==============================] - 0s 10ms/step - loss: 4.1421
Epoch 228/3500
1/1 [==============================] - 0s 5ms/step - loss: 4.0822
Epoch 229/3500
1/1 [==============================] - 0s 0s/step - loss: 4.0231
Epoch 230/3500
1/1 [==============================] - 0s 0s/step - loss: 3.9680
Epoch 231/3500
1/1 [==============================] - 0s 7ms/step - loss: 3.9137
Epoch 232/3500
1/1 [==============================] - 0s 8ms/step - loss: 3.8565
Epoch 233/3500
1/1 [==============================] - 0s 6ms/step - loss: 3.8041
Epoch 234/3500
1/1 [==============================] - 0s 0s/step - loss: 3.7521
Epoch 235/3500
1/1 [==============================] - 0s 10ms/step - loss: 3.7008
Epoch 236/3500
1/1 [==============================] - 0s 3ms/step - loss: 3.6501
Epoch 237/3500
1/1 [==============================] - 0s 2ms/step - loss: 3.6022
Epoch 238/3500
1/1 [==============================] - 0s 0s/step - loss: 3.5522
Epoch 239/3500
1/1 [==============================] - 0s 4ms/step - loss: 3.5050
Epoch 240/3500
1/1 [==============================] - 0s 0s/step - loss: 3.4592
Epoch 241/3500
1/1 [==============================] - 0s 11ms/step - loss: 3.4138
Epoch 242/3500
1/1 [==============================] - 0s 3ms/step - loss: 3.3697
Epoch 243/3500
1/1 [==============================] - 0s 0s/step - loss: 3.3260
Epoch 244/3500

In [12]:
y_pred = model.predict(x_test)

1/1 [==============================] - 0s 80ms/step

In [13]:
from sklearn.metrics import r2_score

In [14]:
r2_score(y_test , y_pred)

-100.88845205898178

In [89]:
df

   cgpa   iq  resume score  package
0     7   90            80        9
1     8   60            60        7
2     9   80            50        8
3     8  102            70        9
4     6   89            90        6
5     5   45            87        7

In [ ]:
def model(x , y):
    w = 0